export enum LPCBodyColor {
	light = 'light',
	amber = 'amber',
	olive = 'olive',
	taupe = 'taupe',
	bronze = 'bronze',
	brown = 'brown',
	black = 'black',
	lavender = 'lavender',
	blue = 'blue',
	bright_green = 'bright_green',
	dark_green = 'dark_green',
	fur_black = 'fur_black',
	fur_brown = 'fur_brown',
	fur_copper = 'fur_copper',
	fur_gold = 'fur_gold',
	fur_grey = 'fur_grey',
	fur_tan = 'fur_tan',
	fur_white = 'fur_white',
	green = 'green',
	pale_green = 'pale_green',
	zombie = 'zombie',
	zombie_green = 'zombie_green'
}